database:
  path: "hostname_cache.db"

dns:
  server: "8.8.8.8"

cache:
  timeout: 3600

jsonDump:
  timeout: 900

cacheCleanup:
  timeout: 3600

logging:
  filename: "log_file.txt"
  format: "%(asctime)s %(levelname)s %(message)s"